/*
 * File: app/controller/ContainerController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.ContainerController', {
    extend: 'Ext.app.Controller',

    models: [
        'Container'
    ],
    stores: [
        'Containers'
    ],
    views: [
        'ContainerGridpanel',
        'ContainerMainpanel',
        'NewContainerWin',
        'EditContainerWin'
    ],

    refs: [
        {
            ref: 'allContainerGrid',
            selector: 'containermainpanel grid'
        }
    ],

    onAddContainerButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.NewContainerWin');

        win.show();
    },

    onEditContainerButtonClick: function(button, e, eOpts) {
        var grid = this.getAllContainerGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditContainerWin');
        			var form = editWin.down('form');
        			//load form
                    form.loadRecord(record[0]);

        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Container to edit');
        		}
    },

    onDeleteContainerButtonClick: function(button, e, eOpts) {
        var grid = this.getAllContainerGrid();
        		var record= grid.getSelectionModel().getSelection();

        if(record[0]){


        	Ext.Msg.show({
                         title:'Delete?',
                         msg: 'Are you sure you want to delete this Container?',
                         buttons: Ext.Msg.YESNO,
                         icon: Ext.Msg.QUESTION,
                         fn: function (buttonId){
                            if (buttonId == 'yes'){
                                Ext.Ajax.request({
                                    url: '/cobuy/index.php?r=Container/DeleteThisContainer',
                                    params: {
                                        id: record[0].get('id')

                                    },
                                    success: function(conn, response, options, eOpts) {

                                        var result = Ext.JSON.decode(conn.responseText);

                                        if (result.success) {

                                            Ext.Msg.alert('Success!', result.msg);
                                            grid.getStore().load();

                                        } else {
                                            var error = Ext.JSON.decode(conn.responseText);
                                            Ext.Msg.alert('Error', error.msg);
                                        }
                                    },
                                    failure: function(conn, response, options, eOpts) {

                                        Ext.Msg.alert('Failure', 'Communication Error');
                                    }
                                });
                            }
                         }
                    });

        }else {
        				Ext.Msg.alert('Error!', 'Please Select a Container to delete');
        		}

    },

    onCancelButtonClick: function(button, e, eOpts) {
        var win = button.up('window');

        win.destroy();
    },

    onSaveNewcontainerButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllContainerGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Container/createnewcontainer',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdittedContainerButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllContainerGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Container/updatecontainer',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onContainerMainpanelGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onEditContainerButtonClick();
    },

    onContainerPanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    init: function(application) {
        this.control({
            "containermainpanel button#addBtn": {
                click: this.onAddContainerButtonClick
            },
            "containermainpanel button#editBtn": {
                click: this.onEditContainerButtonClick
            },
            "containermainpanel button#deleteBtn": {
                click: this.onDeleteContainerButtonClick
            },
            "button#cancelBtn": {
                click: this.onCancelButtonClick
            },
            "newcontainerwin button#addBtn": {
                click: this.onSaveNewcontainerButtonClick
            },
            "editcontainerwin button#addBtn": {
                click: this.onSaveEdittedContainerButtonClick
            },
            "containermainpanel grid": {
                itemdblclick: this.onContainerMainpanelGridpanelItemDblClick
            },
            "containermainpanel": {
                render: this.onContainerPanelRender
            }
        });
    }

});
