/*
 * File: app/controller/CountryController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.CountryController', {
    extend: 'Ext.app.Controller',

    models: [
        'Country'
    ],
    stores: [
        'Countries'
    ],
    views: [
        'CountryGridPanel',
        'CountryMainpanel',
        'NewCountryWin',
        'EditCountryWin'
    ],

    refs: [
        {
            ref: 'allCountryGrid',
            selector: 'countrymainpanel grid'
        }
    ],

    onAddNewCountryButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.NewCountryWin');

        win.show();
    },

    onEditCountryButtonClick: function(button, e, eOpts) {

        var grid = this.getAllCountryGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditCountryWin');
        			var form = editWin.down('form');
        			//load the form
                    form.loadRecord(record[0]);

        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Country to edit');
        		}
    },

    onDeleteCountryButtonClick: function(button, e, eOpts) {
        var grid = this.getAllCountryGrid();
        		var record= grid.getSelectionModel().getSelection();

        if(record[0]){


        	Ext.Msg.show({
                         title:'Delete?',
                         msg: 'Are you sure you want to delete this Country?',
                         buttons: Ext.Msg.YESNO,
                         icon: Ext.Msg.QUESTION,
                         fn: function (buttonId){
                            if (buttonId == 'yes'){
                                Ext.Ajax.request({
                                    url: '/cobuy/index.php?r=Country/DeleteThisCountry',
                                    params: {
                                        id: record[0].get('id')

                                    },
                                    success: function(conn, response, options, eOpts) {

                                        var result = Ext.JSON.decode(conn.responseText);

                                        if (result.success) {

                                            Ext.Msg.alert('Success!', result.msg);
                                            grid.getStore().load();

                                        } else {
                                            var error = Ext.JSON.decode(conn.responseText);
                                            Ext.Msg.alert('Error', error.msg);
                                        }
                                    },
                                    failure: function(conn, response, options, eOpts) {

                                        Ext.Msg.alert('Failure', 'Communication Error');
                                    }
                                });
                            }
                         }
                    });

        }else {
        				Ext.Msg.alert('Error!', 'Please Select a Country to delete');
        		}

    },

    onSaveNewCountryButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllCountryGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Country/createnewcountry',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdittedCountryButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllCountryGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Country/updatecountry',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onCountryMainpanelGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onEditCountryButtonClick();
    },

    onCountryPanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    onJustKiddingButtonClick: function(button, e, eOpts) {
        console.log('just kidding man');
    },

    init: function(application) {
        this.control({
            "countrymainpanel button#addBtn": {
                click: this.onAddNewCountryButtonClick
            },
            "countrymainpanel button#editBtn": {
                click: this.onEditCountryButtonClick
            },
            "countrymainpanel button#deleteBtn": {
                click: this.onDeleteCountryButtonClick
            },
            "newcountrywin button#addBtn": {
                click: this.onSaveNewCountryButtonClick
            },
            "editcountrywin button#addBtn": {
                click: this.onSaveEdittedCountryButtonClick
            },
            "countrymainpanel grid": {
                itemdblclick: this.onCountryMainpanelGridpanelItemDblClick
            },
            "countrymainpanel": {
                render: this.onCountryPanelRender
            },
            "button#justkiddingBtn": {
                click: this.onJustKiddingButtonClick
            }
        });
    }

});
