/*
 * File: app/controller/DeliveryOnTransitController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.DeliveryOnTransitController', {
    extend: 'Ext.app.Controller',

    models: [
        'OrderDelivery'
    ],
    stores: [
        'OrderDeliveries'
    ],
    views: [
        'DeliveriesOnTransitMainpanel',
        'ViewDeliveriesOnTransitWin'
    ],

    refs: [
        {
            ref: 'allDeliveriesOnTransitGrid',
            selector: 'deliveriesontransitmainpanel grid'
        }
    ],

    onViewDeliveryOnTransitButtonClick: function(button, e, eOpts) {
        var grid = this.getAllDeliveriesOnTransitGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.ViewDeliveriesOnTransitWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=OrderDelivery/retrieveDeliveredOrderDetails',
        			     params: {
        					order_id: record[0].get('order_id'),
                            member_id: record[0].get('member_id'),
                            order_assigned_by: record[0].get('order_assigned_by'),
                             order_assigned_to: record[0].get('order_assigned_to'),
                             date_of_assignment:record[0].get('date_of_assignment')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var delivery_status = jsonResponse.delivery_status;
                                var member_remark = jsonResponse.member_remark;
                                var order_number = jsonResponse.order_number;
                                var order_assigned_by = jsonResponse.order_assigned_by;
                                var delivered_by = jsonResponse.delivered_by;
                                var delivery_confirmed_by = jsonResponse.delivered_confirmed_by;
                                var date_of_delivery_confirmation = jsonResponse.date_of_delivery_confirmation;
                                var member = jsonResponse.member;



        					}

        					var values = {

                                order_number:order_number,
                                member_remark:member_remark,
                                delivery_status:delivery_status,
                                order_assigned_by:order_assigned_by,
                                delivered_by:delivered_by,
                                delivery_confirmed_by:delivery_confirmed_by,
                                date_of_delivery_confirmation:date_of_delivery_confirmation



        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select an order on transit to view');
        		}
    },

    onViewingThisDeliveryOnTransitButtonClick: function(button, e, eOpts) {
        var win = button.up('window');

        win.destroy();
    },

    onDeliveryOnTransitGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onViewDeliveryOnTransitButtonClick();
    },

    onUpdateDeliveryOnTransitButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllDeliveriesOnTransitGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=OrderDelivery/updateDeliverOnTransit',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onDeliveriesOnTransitPanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    init: function(application) {
        this.control({
            "deliveriesontransitmainpanel button#viewBtn": {
                click: this.onViewDeliveryOnTransitButtonClick
            },
            "viewdeliveriesontransitwin button#viewBtn": {
                click: this.onViewingThisDeliveryOnTransitButtonClick
            },
            "deliveriesontransitmainpanel grid": {
                itemdblclick: this.onDeliveryOnTransitGridpanelItemDblClick
            },
            "viewdeliveriesontransitwin button#updatedeliveryBtn": {
                click: this.onUpdateDeliveryOnTransitButtonClick
            },
            "deliveriesontransitmainpanel": {
                render: this.onDeliveriesOnTransitPanelRender
            }
        });
    }

});
