/*
 * File: app/controller/DeliveriesOnDisputeController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.DeliveriesOnDisputeController', {
    extend: 'Ext.app.Controller',

    models: [
        'OrderDelivery'
    ],
    stores: [
        'OrderDeliveries'
    ],
    views: [
        'DeliveryOnDisputeMainpanel',
        'ViewDeliveryOnDisputeWin'
    ],

    refs: [
        {
            ref: 'allDeliveriesOnDisputeGrid',
            selector: 'deliveryondisputemainpanel grid'
        }
    ],

    onViewDeliveryOnDisputeButtonClick: function(button, e, eOpts) {
        var grid = this.getAllDeliveriesOnDisputeGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.ViewDeliveryOnDisputeWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=OrderDelivery/retrieveDeliveredOrderDetails',
        			     params: {
        					order_id: record[0].get('order_id'),
                            member_id: record[0].get('member_id'),
                           order_assigned_by: record[0].get('order_assigned_by'),
                             order_assigned_to: record[0].get('order_assigned_to'),
                             date_of_assignment:record[0].get('date_of_assignment')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var delivery_status = jsonResponse.delivery_status;
                                var member_remark = jsonResponse.member_remark;
                                var order_number = jsonResponse.order_number;
                                var order_assigned_by = jsonResponse.order_assigned_by;
                                var delivered_by = jsonResponse.order_delivered_by;
                                var member = jsonResponse.member;
                                var date_of_delivery = jsonResponse.date_of_delivery;
                                var delivery_confirmed_by = jsonResponse.delivered_confirmed_by;
                                var date_of_delivery_confirmation = jsonResponse.date_of_delivery_confirmation;

                                console.log('date of delivery is:',date_of_delivery);

        					}

        					var values = {

                                order_number:order_number,
                                member_remark:member_remark,
                                delivery_status:delivery_status,
                                order_assigned_by:order_assigned_by,
                                order_delivered_by:delivered_by,
                                date_of_delivery:date_of_delivery,
                                delivery_confirmed_by:delivery_confirmed_by,
                                date_of_delivery_confirmation:date_of_delivery_confirmation




        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select an order delivery on disute to view');
        		}
    },

    onViewingThisDeliveryOnDisputeButtonClick: function(button, e, eOpts) {
        var win = button.up('window');

        win.destroy();
    },

    onDeliveryOnDisputeGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onViewDeliveryOnDisputeButtonClick();
    },

    onDeliveryOnDisputePanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    init: function(application) {
        this.control({
            "deliveryondisputemainpanel button#viewBtn": {
                click: this.onViewDeliveryOnDisputeButtonClick
            },
            "viewdeliveryondisputewin button#viewBtn": {
                click: this.onViewingThisDeliveryOnDisputeButtonClick
            },
            "deliveryondisputemainpanel grid": {
                itemdblclick: this.onDeliveryOnDisputeGridpanelItemDblClick
            },
            "deliveryondisputemainpanel": {
                render: this.onDeliveryOnDisputePanelRender
            }
        });
    }

});
