/*
 * File: app/controller/FailedPaymentController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.FailedPaymentController', {
    extend: 'Ext.app.Controller',

    models: [
        'Payment'
    ],
    stores: [
        'Payments'
    ],
    views: [
        'FailedPaymentMainpanel',
        'TheFailedPaymentWin'
    ],

    refs: [
        {
            ref: 'allFailedPaymentsGrid',
            selector: 'failedpaymentmainpanel grid'
        }
    ],

    onViewFailedPaymentButtonClick: function(button, e, eOpts) {
        var grid = this.getAllFailedPaymentsGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.TheFailedPaymentWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=Payment/retrievePaymentDetailsForUpdate',
        			     params: {
        					id: record[0].get('id'),
                            order_id:record[0].get('order_id'),
                             bank_account_id:record[0].get('bank_account_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var bank_account = jsonResponse.bank_number;
                                var order_number = jsonResponse.order_number;
                                var payee = jsonResponse.payee;
                                var amount_in_bank= record[0].get('gross_amount') + record[0].get('delivery_charges');


        					}

        					var values = {

                                bank_account:bank_account,
                                order_number:order_number,
                                payee:payee,
                                gross_amount_for_display:Ext.util.Format.number(record[0].get('gross_amount'),'0,000.00'),
                                net_amount_for_display:Ext.util.Format.number(record[0].get('net_amount'),'0,000.00'),
                                discounted_amount_for_display:Ext.util.Format.number(record[0].get('discounted_amount'),'0,000.00'),
                                vat_for_display:Ext.util.Format.number(record[0].get('vat'),'0,000.00'),
                                revenue_for_display:Ext.util.Format.number(record[0].get('revenue'),'0,000.00'),
                                delivery_charges:Ext.util.Format.number(record[0].get('delivery_charges'),'0,000.00'),
                                amount_in_bank:Ext.util.Format.number(amount_in_bank,'0,000.00')





        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a failed Payment to view');
        		}
    },

    onViewingThisFailedPaymentButtonClick: function(button, e, eOpts) {
        var win = button.up('window');

        win.destroy();
    },

    onFailedPaymentPanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    onFailedPaymentGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onViewFailedPaymentButtonClick();
    },

    init: function(application) {
        this.control({
            "failedpaymentmainpanel button#viewBtn": {
                click: this.onViewFailedPaymentButtonClick
            },
            "thefailedpaymentwin button#okBtn": {
                click: this.onViewingThisFailedPaymentButtonClick
            },
            "failedpaymentmainpanel": {
                render: this.onFailedPaymentPanelRender
            },
            "failedpaymentmainpanel grid": {
                itemdblclick: this.onFailedPaymentGridpanelItemDblClick
            }
        });
    }

});
