/*
 * File: app/controller/HamperContainerController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.HamperContainerController', {
    extend: 'Ext.app.Controller',

    models: [
        'HamperContainers'
    ],
    stores: [
        'AllHamperContainers'
    ],

    refs: [
        {
            ref: 'allHamperContainersGrid',
            selector: 'hampercontainersmainpanel grid'
        }
    ],

    onHamperContainerWindowRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    onAddNewHamperContainerButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.NewHamperContainerWin');

        win.show();
    },

    onEditHamperContainerButtonClick: function(button, e, eOpts) {
        var grid = this.getAllHamperContainersGrid(),
        		record = grid.getSelectionModel().getSelection();

        if(record[0]){

            var win = Ext.create('cobuy.view.EditHamperContainerWin');
            var form = win.down('form');
            form.loadRecord(record[0]);
            win.show();
        }else{
           Ext.Msg.alert('Error', 'Please select a hamper container to edit');
        }

    },

    onDeleteHamperContainerButtonClick: function(button, e, eOpts) {
        var grid = this.getAllHamperContainersGrid();
        		var record= grid.getSelectionModel().getSelection();

        if(record[0]){


        	Ext.Msg.show({
                         title:'Delete?',
                         msg: 'Are you sure you want to remove this hamper container?',
                         buttons: Ext.Msg.YESNO,
                         icon: Ext.Msg.QUESTION,
                         fn: function (buttonId){
                            if (buttonId == 'yes'){
                                Ext.Ajax.request({
                                    url: '/cobuy/index.php?r=HamperContainer/removeThisHamperContainer',
                                    params: {
                                        id: record[0].get('id')

                                    },
                                    success: function(conn, response, options, eOpts) {

                                        var result = Ext.JSON.decode(conn.responseText);

                                        if (result.success) {

                                            Ext.Msg.alert('Success!', result.msg);
                                            grid.getStore().load();

                                        } else {
                                            var error = Ext.JSON.decode(conn.responseText);
                                            Ext.Msg.alert('Error', error.msg);
                                        }
                                    },
                                    failure: function(conn, response, options, eOpts) {

                                        Ext.Msg.alert('Failure', 'Communication Error');
                                    }
                                });
                            }
                         }
                    });

        }else {
        				Ext.Msg.alert('Error', 'Please Select the hamper container you want to remove');
        		}

    },

    onHamperContainerGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onEditHamperContainerButtonClick();
    },

    onSaveNewHamperContainerButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllHamperContainersGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=HamperContainer/AddNewHamperContainer',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdittedHamperContainerInfoButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllHamperContainersGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=HamperContainer/UpdateNewHamperContainer',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    init: function(application) {
        this.control({
            "hampercontainersmainpanel": {
                render: this.onHamperContainerWindowRender
            },
            "hampercontainersmainpanel button#addcontainerBtn": {
                click: this.onAddNewHamperContainerButtonClick
            },
            "hampercontainersmainpanel button#edithamperBtn": {
                click: this.onEditHamperContainerButtonClick
            },
            "hampercontainersmainpanel button#deletehamperBtn": {
                click: this.onDeleteHamperContainerButtonClick
            },
            "hampercontainersmainpanel grid": {
                itemdblclick: this.onHamperContainerGridpanelItemDblClick
            },
            "newhampercontainerwin button#saveBtn": {
                click: this.onSaveNewHamperContainerButtonClick
            },
            "edithampercontainerwin button#saveBtn": {
                click: this.onSaveEdittedHamperContainerInfoButtonClick
            }
        });
    }

});
