/*
 * File: app/controller/IncompleteOrdersController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.IncompleteOrdersController', {
    extend: 'Ext.app.Controller',

    models: [
        'Order'
    ],
    stores: [
        'Orders'
    ],
    views: [
        'IncompleteOrdersMainpanel',
        'TheIncompleteOrderWin'
    ],

    refs: [
        {
            ref: 'allIncompleteOrdersGrid',
            selector: 'incompleteordersmainpanel grid'
        }
    ],

    onViewIncompleteOrdersButtonClick: function(button, e, eOpts) {
        var grid = this.getAllIncompleteOrdersGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.TheIncompleteOrderWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=Order/retrieveOrderDetails',
        			     params: {
        					order_initiated_by: record[0].get('order_initiated_by'),
                             delivery_city_id:record[0].get('delivery_city_id'),
                             delivery_state_id:record[0].get('delivery_state_id'),
                             delivery_country_id:record[0].get('delivery_country_id'),
                              order_id:record[0].get('id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var requester = jsonResponse.requester;
                                var country = jsonResponse.country;
                                var state = jsonResponse.state;
                                var city = jsonResponse.city;
                                 var payment_status=jsonResponse.payment_status;
                                var delivery_type=jsonResponse.delivery_type;



        					}

        					var values = {

                                requester:requester,
                                city:city,
                                state:state,
                                country:country,
                                payment_status:payment_status,
                                order_delivery_type:delivery_type


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select an Order');
        		}
    },

    onViewThisInCompleteOrderButtonClick: function(button, e, eOpts) {
        var win = button.up('window');

        win.destroy();
    },

    onIncompleteOrderGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        //this.onViewIncompleteOrdersButtonClick();

        var order_id = record.get('id');

        var status = record.get('status');

        console.log('the order id is;',order_id);

        console.log('the status is:',status);

        var win = Ext.create('cobuy.view.ProductsInOrderWin');

        var form = win.down('#orderidform');

        var values = {
            order_id:order_id,
            status:status
        };

        form.getForm().setValues(values);

        win.show();
    },

    onIncompleteOrdersPanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    onProductsInCartWindowRender: function(component, eOpts) {
        var order_id = component.down('#orderidform').down('hiddenfield[name=order_id]').getValue();

        var status = component.down('#orderidform').down('hiddenfield[name=status]').getValue();

        console.log('order_id isss;', order_id);

        console.log('status isss:', status);

        if(status == 'open'){
            component.down('#addBtn').setDisabled(false);
            component.down('#editBtn').setDisabled(false);
            component.down('#deleteBtn').setDisabled(false);
        }

        //load the grid

        component.down('grid').getStore().load({
            params:{
                order_id:order_id
            }
        });
    },

    init: function(application) {
        this.control({
            "incompleteordersmainpanel button#viewBtn": {
                click: this.onViewIncompleteOrdersButtonClick
            },
            "theIncompleteorderwin button#viewBtn": {
                click: this.onViewThisInCompleteOrderButtonClick
            },
            "incompleteordersmainpanel grid": {
                itemdblclick: this.onIncompleteOrderGridpanelItemDblClick
            },
            "incompleteordersmainpanel": {
                render: this.onIncompleteOrdersPanelRender
            },
            "productsinorderwin": {
                render: this.onProductsInCartWindowRender
            }
        });
    }

});
