/*
 * File: app/controller/ServicesController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.ServicesController', {
    extend: 'Ext.app.Controller',

    models: [
        'Service'
    ],
    stores: [
        'Services'
    ],
    views: [
        'ServicesGridpanel',
        'ServiceMainpanel',
        'NewServiceWin',
        'EditServiceWin'
    ],

    refs: [
        {
            ref: 'allServicesGrid',
            selector: 'servicemainpanel grid'
        }
    ],

    onAddSeviceButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.NewServiceWin');

        win.show();
    },

    onEditServiceButtonClick: function(button, e, eOpts) {
        var grid = this.getAllServicesGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditServiceWin');
        			var form = editWin.down('form');
        			//var grouptype_id = record[0].get('grouptype_id');

        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=Service/obtainServiceExtraInformation',
        			     params: {
        					container_id: record[0].get('container_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

        					var container_name = jsonResponse.container;



        					}

        					var values = {
        						//grouptype_id: grouptype_name,
        						container: container_name


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Service to edit');
        		}
    },

    onDeleteServiceButtonClick: function(button, e, eOpts) {
        var grid = this.getAllServicesGrid();
        		var record= grid.getSelectionModel().getSelection();

        if(record[0]){


        	Ext.Msg.show({
                         title:'Delete?',
                         msg: 'Are you sure you want to delete this Service?',
                         buttons: Ext.Msg.YESNO,
                         icon: Ext.Msg.QUESTION,
                         fn: function (buttonId){
                            if (buttonId == 'yes'){
                                Ext.Ajax.request({
                                    url: '/cobuy/index.php?r=Service/DeleteThisService',
                                    params: {
                                        id: record[0].get('id')

                                    },
                                    success: function(conn, response, options, eOpts) {

                                        var result = Ext.JSON.decode(conn.responseText);

                                        if (result.success) {

                                            Ext.Msg.alert('Success!', result.msg);
                                            grid.getStore().load();

                                        } else {
                                            var error = Ext.JSON.decode(conn.responseText);
                                            Ext.Msg.alert('Error', error.msg);
                                        }
                                    },
                                    failure: function(conn, response, options, eOpts) {

                                        Ext.Msg.alert('Failure', 'Communication Error');
                                    }
                                });
                            }
                         }
                    });

        }else {
        				Ext.Msg.alert('Error', 'Please Select a Service to delete');
        		}

    },

    onSaveNewServiceButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllServicesGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Service/createNewService',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdiitedServiceButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllServicesGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Service/updateService',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onServiceGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onEditServiceButtonClick();
    },

    onServicePanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();

        //reconfigure this grid


    },

    init: function(application) {
        this.control({
            "servicemainpanel button#addBtn": {
                click: this.onAddSeviceButtonClick
            },
            "servicemainpanel button#editBtn": {
                click: this.onEditServiceButtonClick
            },
            "servicemainpanel button#deleteBtn": {
                click: this.onDeleteServiceButtonClick
            },
            "newservicewin button#addBtn": {
                click: this.onSaveNewServiceButtonClick
            },
            "editservicewin button#addBtn": {
                click: this.onSaveEdiitedServiceButtonClick
            },
            "servicemainpanel grid": {
                itemdblclick: this.onServiceGridpanelItemDblClick
            },
            "servicemainpanel": {
                render: this.onServicePanelRender
            }
        });
    }

});
