/*
 * File: app/controller/SubscriptionFeesController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.SubscriptionFeesController', {
    extend: 'Ext.app.Controller',

    models: [
        'MembershipFee'
    ],
    stores: [
        'MembershipFees'
    ],
    views: [
        'MembershipFeeGridPanel',
        'MembershipFeeMainpanel',
        'NewMembershipFeeWin',
        'EditMembershipFeeWin'
    ],

    refs: [
        {
            ref: 'allMembershipFeesGrid',
            selector: 'membershipfeemainpanel grid'
        }
    ],

    onAddMembershipTypeFeeButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.NewMembershipFeeWin');

        win.show();
    },

    onEditMembershipTypeFeeButtonClick: function(button, e, eOpts) {
        var grid = this.getAllMembershipFeesGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditMembershipFeeWin');
        			var form = editWin.down('form');
                    form.loadRecord(record[0]);
        		editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Membership fee to edit');
        		}
    },

    onDeleteMembershipTypeFeeButtonClick: function(button, e, eOpts) {
        var grid = this.getAllMembershipFeesGrid();
        		var record= grid.getSelectionModel().getSelection();

        if(record[0]){


        	Ext.Msg.show({
                         title:'Delete?',
                         msg: 'Are you sure you want to delete this Subscription Fee?',
                         buttons: Ext.Msg.YESNO,
                         icon: Ext.Msg.QUESTION,
                         fn: function (buttonId){
                            if (buttonId == 'yes'){
                                Ext.Ajax.request({
                                    url: '/cobuy/index.php?r=MembershipFee/DeleteThisMembershipFee',
                                    params: {
                                        id: record[0].get('id')

                                    },
                                    success: function(conn, response, options, eOpts) {

                                        var result = Ext.JSON.decode(conn.responseText);

                                        if (result.success) {

                                            Ext.Msg.alert('Success!', result.msg);
                                            grid.getStore().load();

                                        } else {
                                            var error = Ext.JSON.decode(conn.responseText);
                                            Ext.Msg.alert('Error', error.msg);
                                        }
                                    },
                                    failure: function(conn, response, options, eOpts) {

                                        Ext.Msg.alert('Failure', 'Communication Error');
                                    }
                                });
                            }
                         }
                    });

        }else {
        				Ext.Msg.alert('Error', 'Please Select a Subscription  fee to delete');
        		}

    },

    onSaveNewMembershipTypeFeeButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllMembershipFeesGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipFee/createNewMembershipFee',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdittedMembershipTypeFeeButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllMembershipFeesGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipFee/updateMembershipFee',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onMembershipTypeSubscriptionFeeGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onEditMembershipTypeFeeButtonClick();
    },

    onMembershipFeePanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    onMonthlyFeeComboboxSelect: function(combo, records, eOpts) {
        var win = combo.up('window');


        var value = {
            yearly_fee:combo.getValue()
        };

        //set the yearly combo value

        win.down('form').getForm().setValues(value);


    },

    init: function(application) {
        this.control({
            "membershipfeemainpanel button#addBtn": {
                click: this.onAddMembershipTypeFeeButtonClick
            },
            "membershipfeemainpanel button#editBtn": {
                click: this.onEditMembershipTypeFeeButtonClick
            },
            "membershipfeemainpanel button#deleteBtn": {
                click: this.onDeleteMembershipTypeFeeButtonClick
            },
            "newmembershipfeewin button#addBtn": {
                click: this.onSaveNewMembershipTypeFeeButtonClick
            },
            "editmembershipfeewin button#addBtn": {
                click: this.onSaveEdittedMembershipTypeFeeButtonClick
            },
            "membershipfeemainpanel grid": {
                itemdblclick: this.onMembershipTypeSubscriptionFeeGridpanelItemDblClick
            },
            "membershipfeemainpanel": {
                render: this.onMembershipFeePanelRender
            },
            "combobox#monthlyFeeCombo": {
                select: this.onMonthlyFeeComboboxSelect
            }
        });
    }

});
