/*
 * File: app/controller/SubscriptionController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.SubscriptionController', {
    extend: 'Ext.app.Controller',

    models: [
        'MembershipSubscription'
    ],
    stores: [
        'MembershipSubscriptions'
    ],
    views: [
        'MembershipSubscriptionMainpanel',
        'NewMembershipSubscriptionWin',
        'EditMembershipSubscriptionWin',
        'ActivateMembershipSubscriptionWin',
        'DeactivateMembershipSubscriptionWin',
        'SuspendMembershipSubscriptionWin'
    ],

    refs: [
        {
            ref: 'allSubscriptionGrid',
            selector: 'membershipsubscriptionmainpanel grid'
        }
    ],

    onAddMemberSubscriptionButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.NewMembershipSubscriptionWin');

        win.show();
    },

    onEditMembershipSubscriptionButtonClick: function(button, e, eOpts) {
        var grid = this.getAllSubscriptionGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditMembershipSubscriptionWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=MembershipSubscription/obtainSubscriptionExtraInformation',
        			     params: {
                            member_id: record[0].get('member_id'),
                            membership_type_id: record[0].get('membership_type_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var member_name = jsonResponse.member;
                                var membership_type = jsonResponse.membership;




        					}

        					var values = {

        						name: member_name,
        						membertype: membership_type


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Membership Subscription to edit');
        		}
    },

    onExtendMembershipSubscriptionButtonClick: function(button, e, eOpts) {
        var grid = this.getAllSubscriptionGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.ExtendingSubscriptionWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=MembershipSubscription/obtainSubscriptionExtraInformation',
        			     params: {
                            member_id: record[0].get('member_id'),
                            membership_type_id: record[0].get('membership_type_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var member_name = jsonResponse.member;
                                var membership_type = jsonResponse.membership;


        					}

        					var values = {

        						name: member_name,
        						membertype: membership_type


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Membership Subscription to activate');
        		}
    },

    onSaveNewMembershipSubscriptionButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllSubscriptionGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipSubscription/addNewMembershipSubscription',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdittedMembershipSubscriptionButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllSubscriptionGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipSubscription/updateMembershipSubscription',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onMembershipSubscriptionGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onEditMembershipSubscriptionButtonClick();
    },

    onActivateMembershipSubscriptionButtonClick: function(button, e, eOpts) {
        var grid = this.getAllSubscriptionGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.ActivateMembershipSubscriptionWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=MembershipSubscription/obtainSubscriptionExtraInformation',
        			     params: {
                            member_id: record[0].get('member_id'),
                            membership_type_id: record[0].get('membership_type_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var member_name = jsonResponse.member;
                                var membership_type = jsonResponse.membership;


        					}

        					var values = {

        						name: member_name,
        						membertype: membership_type


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Membership Subscription to activate');
        		}
    },

    onSaveTheActivationOfThisMemberSubscriptionButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllSubscriptionGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipSubscription/activateMembershipSubscription',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onDeactivateMembershipSubscriptionButtonClick: function(button, e, eOpts) {
        var grid = this.getAllSubscriptionGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.DeactivateMembershipSubscriptionWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=MembershipSubscription/obtainSubscriptionExtraInformation',
        			     params: {
                            member_id: record[0].get('member_id'),
                            membership_type_id: record[0].get('membership_type_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var member_name = jsonResponse.member;
                                var membership_type = jsonResponse.membership;


        					}

        					var values = {

        						name: member_name,
        						membertype: membership_type


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Membership Subscription to deactivate');
        		}
    },

    onSaveTheDeatctivationOfThisMemberSubscriptionButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllSubscriptionGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipSubscription/deactivateMembershipSubscription',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSuspendMembershipSubscriptionButtonClick: function(button, e, eOpts) {
        var grid = this.getAllSubscriptionGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.SuspendMembershipSubscriptionWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=MembershipSubscription/obtainSubscriptionExtraInformation',
        			     params: {
                            member_id: record[0].get('member_id'),
                            membership_type_id: record[0].get('membership_type_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var member_name = jsonResponse.member;
                                var membership_type = jsonResponse.membership;


        					}

        					var values = {

        						name: member_name,
        						membertype: membership_type


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Membership Subscription to suspend');
        		}
    },

    onSaveTheSuspensionOfThisMemberSubscriptionButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllSubscriptionGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipSubscription/suspendMembershipSubscription',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveExtendedSubscriptionButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllSubscriptionGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipSubscription/extendMembershipSubscription',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onRenewSubcriptionButtonClick: function(button, e, eOpts) {
        var grid = this.getAllSubscriptionGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.RenewSubscriptionWin');
        			var form = editWin.down('form');


        			Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=MembershipSubscription/obtainSubscriptionExtraInformation',
        			     params: {
                            member_id: record[0].get('member_id'),
                            membership_type_id: record[0].get('membership_type_id')
        				},
                     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var member_name = jsonResponse.member;
                                var membership_type = jsonResponse.membership;


        					}

        					var values = {

        						name: member_name,
        						membertype: membership_type


        					};


        					form.loadRecord(record[0]);

        					form.getForm().setValues(values);


        				}




        			});


        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error!', 'Please Select a Membership Subscription to Renew');
        		}
    },

    onSaveTheRenewalOfThisSubscriptionButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllSubscriptionGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=MembershipSubscription/renewMembershipSubscription',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onMembershipSubscriptionPanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    init: function(application) {
        this.control({
            "membershipsubscriptionmainpanel button#addBtn": {
                click: this.onAddMemberSubscriptionButtonClick
            },
            "membershipsubscriptionmainpanel button#editBtn": {
                click: this.onEditMembershipSubscriptionButtonClick
            },
            "membershipsubscriptionmainpanel button#extendBtn": {
                click: this.onExtendMembershipSubscriptionButtonClick
            },
            "newmembershipsubscriptionwin button#addBtn": {
                click: this.onSaveNewMembershipSubscriptionButtonClick
            },
            "editmembershipsubscriptionwin button#addBtn": {
                click: this.onSaveEdittedMembershipSubscriptionButtonClick
            },
            "membershipsubscriptionmainpanel grid": {
                itemdblclick: this.onMembershipSubscriptionGridpanelItemDblClick
            },
            "membershipsubscriptionmainpanel button#activateBtn": {
                click: this.onActivateMembershipSubscriptionButtonClick
            },
            "activatemembershipsubscriptionwin button#activateBtn": {
                click: this.onSaveTheActivationOfThisMemberSubscriptionButtonClick
            },
            "membershipsubscriptionmainpanel button#deactivateBtn": {
                click: this.onDeactivateMembershipSubscriptionButtonClick
            },
            "deactivatemembershipsubscriptionwin button#deactivateBtn": {
                click: this.onSaveTheDeatctivationOfThisMemberSubscriptionButtonClick
            },
            "membershipsubscriptionmainpanel button#suspendBtn": {
                click: this.onSuspendMembershipSubscriptionButtonClick
            },
            "suspendmembershipsubscriptionwin button#suspendBtn": {
                click: this.onSaveTheSuspensionOfThisMemberSubscriptionButtonClick
            },
            "extendingsubscriptionwin button#extendBtn": {
                click: this.onSaveExtendedSubscriptionButtonClick
            },
            "membershipsubscriptionmainpanel button#renewBtn": {
                click: this.onRenewSubcriptionButtonClick
            },
            "renewsubscriptionwin button#renewBtn": {
                click: this.onSaveTheRenewalOfThisSubscriptionButtonClick
            },
            "membershipsubscriptionmainpanel": {
                render: this.onMembershipSubscriptionPanelRender
            }
        });
    }

});
