/*
 * File: app/controller/TaskController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.TaskController', {
    extend: 'Ext.app.Controller',

    models: [
        'Task'
    ],
    stores: [
        'Tasks'
    ],
    views: [
        'TasksMain',
        'NewTaskWin',
        'EditTaskWin',
        'AssignTaskWin'
    ],

    refs: [
        {
            ref: 'allTasksGrid',
            selector: 'tasksmain grid'
        }
    ],

    onCreateNewTaskButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.NewTaskWin');

        win.show();
    },

    onEditTaskButtonClick: function(button, e, eOpts) {
        var grid = this.getAllTasksGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditTaskWin');
        			editWin.down('form').loadRecord(record[0]);
        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error', 'Please Select a Task to edit');
                }
    },

    onAssignTaskButtonClick: function(button, e, eOpts) {
        var grid = this.getAllTasksGrid();
        		var record = grid.getSelectionModel().getSelection();


        		if(record[0]){
        			var win = Ext.create('cobuy.view.AssignTaskWin');
        			var form = win.down('form');
        			var task_container =form.down('#taskCheckbox');
        			var operation_container =form.down('#operationCheckbox');
        			//var user_name = record[0].get('firstname')+ ' ' + record[0].get('middlename') + ' ' + record[0].get('lastname');
        			var task_name = record[0].get('name');



        			Ext.Ajax.request({
                      url: '/cobuy/index.php?r=Authitem/Listalltasksanditschildren',
        				params: {
        					task_name: record[0].get('name')
        					//role_type: record[0].get('type')
        				},
                     //success or failure

        			success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);


        				//checkboxgroup for operations
        					var checkboxGroup_operation = {
                                 xtype: 'checkboxgroup',
                                 columns: 1,
                                  vertical: true,
                                  width: 500,
                                 //fieldLabel: 'Authorisation',
                                 //name: 'recipients',
                                 style: {
                                       padding: '5px 10px 5px 10px'
                                 },
                           items: []

                      };

        			  //checkboxgroup for task
        			  var checkboxGroup_task = {
                                 xtype: 'checkboxgroup',
                                 columns: 1,
                                  vertical: true,
                                  width: 500,
                                 //fieldLabel: 'Authorisation',
                                 //name: 'recipients',
                                 style: {
                                       padding: '5px 10px 5px 10px'
                                 },
                           items: []

                      };



                       var i, j, k,  len = jsonResponse.authitems.length, item, children, length = jsonResponse.children.length, name, select_value, operations,
        			   roles, tasks;

        			  for (i=0; i < len; i++) {
        					item = jsonResponse.authitems[i];
        					if(item.type == 0) {
        						for( j = 0; j < length; j++){
        							children = jsonResponse.children[j];
        							if(children.child === item.name){
        								item.select_value = children.child;
        								name = task_name;

        							}


        						}//end of the j for loop statement
        						checkboxGroup_operation.items.push({
        							xtype: 'checkbox',
        							boxLabel: item.name,
        							name: 'child[]',
        							inputValue: item.name,
        							checked: item.select_value

        						});




        					}//end of the item.type if statement



        			   } //end of the i for loop
        			   operation_container.add(checkboxGroup_operation);

        			  for (i=0; i < len; i++) {
        					item = jsonResponse.authitems[i];
        					if(item.name === task_name){
        									continue;
        						}
        					if(item.type == 1) {
        						for( j = 0; j < length; j++){
        							children = jsonResponse.children[j];
        							if(children.child === item.name){
        								item.select_value = children.child;
        								name = task_name;

        							}


        						}//end of the j for loop statement
        						checkboxGroup_task.items.push({
        							xtype: 'checkbox',
        							boxLabel: item.name,
        							name: 'child[]',
        							inputValue: item.name,
        							checked: item.select_value

        						});




        					}//end of the item.type if statement



        			   } //end of the i for loop
        			   task_container.add(checkboxGroup_task);


        			   var values = {
        				name: task_name

        				};


        		   //form.loadRecord(record[0]);

        		   form.getForm().setValues(values);

        			}



        			});

        			win.show();


        		} else {
        				Ext.Msg.alert('Error', 'Please Select a Task ');

        		}
    },

    onDeleteTaskButtonClick: function(button, e, eOpts) {
        var grid = this.getAllTasksGrid();
        		var record= grid.getSelectionModel().getSelection();

        if(record[0]){


        	Ext.Msg.show({
                         title:'Delete?',
                         msg: 'Are you sure you want to delete this Task?',
                         buttons: Ext.Msg.YESNO,
                         icon: Ext.Msg.QUESTION,
                         fn: function (buttonId){
                            if (buttonId == 'yes'){
                                Ext.Ajax.request({
                                    url: '/cobuy/index.php?r=Authitem/deleteoneauthitem',
                                    params: {
                                        id: record[0].get('id')

                                    },
                                    success: function(conn, response, options, eOpts) {

                                        var result = Ext.JSON.decode(conn.responseText);

                                        if (result.success) {

                                            Ext.Msg.alert('Success!', result.msg);
                                            grid.getStore().load();

                                        } else {
                                            var error = Ext.JSON.decode(conn.responseText);
                                            Ext.Msg.alert('Error', error.msg);
                                        }
                                    },
                                    failure: function(conn, response, options, eOpts) {

                                        Ext.Msg.alert('Failure', 'Communication Error');
                                    }
                                });
                            }
                         }
                    });

        }else {
        				Ext.Msg.alert('Error', 'Please Select a User Task to delete');
        		}

    },

    onSaveCreatedTaskButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllTasksGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Authitem/createnewtaskitem',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdittedTaskButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllTasksGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Authitem/updatetaskitem',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveAssignedTaskButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getallRolesGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=Authitem/assignauthitemstotasks',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onTaskGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var grid = this.getAllTasksGrid();
        		var record = grid.getSelectionModel().getSelection();


        		if(record[0]){
        			var win = Ext.create('cobuy.view.AssignTaskWin');
        			var form = win.down('form');
        			var task_container =form.down('#taskCheckbox');
        			var operation_container =form.down('#operationCheckbox');
        			//var user_name = record[0].get('firstname')+ ' ' + record[0].get('middlename') + ' ' + record[0].get('lastname');
        			var task_name = record[0].get('name');



        			Ext.Ajax.request({
                      url: '/cobuy/index.php?r=Authitem/Listalltasksanditschildren',
        				params: {
        					task_name: record[0].get('name')
        					//role_type: record[0].get('type')
        				},
                     //success or failure

        			success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);


        				//checkboxgroup for operations
        					var checkboxGroup_operation = {
                                 xtype: 'checkboxgroup',
                                 columns: 1,
                                  vertical: true,
                                  width: 500,
                                 //fieldLabel: 'Authorisation',
                                 //name: 'recipients',
                                 style: {
                                       padding: '5px 10px 5px 10px'
                                 },
                           items: []

                      };

        			  //checkboxgroup for task
        			  var checkboxGroup_task = {
                                 xtype: 'checkboxgroup',
                                 columns: 1,
                                  vertical: true,
                                  width: 500,
                                 //fieldLabel: 'Authorisation',
                                 //name: 'recipients',
                                 style: {
                                       padding: '5px 10px 5px 10px'
                                 },
                           items: []

                      };



                       var i, j, k,  len = jsonResponse.authitems.length, item, children, length = jsonResponse.children.length, name, select_value, operations,
        			   roles, tasks;

        			  for (i=0; i < len; i++) {
        					item = jsonResponse.authitems[i];
        					if(item.type == 0) {
        						for( j = 0; j < length; j++){
        							children = jsonResponse.children[j];
        							if(children.child === item.name){
        								item.select_value = children.child;
        								name = task_name;

        							}


        						}//end of the j for loop statement
        						checkboxGroup_operation.items.push({
        							xtype: 'checkbox',
        							boxLabel: item.name,
        							name: 'child[]',
        							inputValue: item.name,
        							checked: item.select_value

        						});




        					}//end of the item.type if statement



        			   } //end of the i for loop
        			   operation_container.add(checkboxGroup_operation);

        			  for (i=0; i < len; i++) {
        					item = jsonResponse.authitems[i];
        					if(item.name === task_name){
        									continue;
        						}
        					if(item.type == 1) {
        						for( j = 0; j < length; j++){
        							children = jsonResponse.children[j];
        							if(children.child === item.name){
        								item.select_value = children.child;
        								name = task_name;

        							}


        						}//end of the j for loop statement
        						checkboxGroup_task.items.push({
        							xtype: 'checkbox',
        							boxLabel: item.name,
        							name: 'child[]',
        							inputValue: item.name,
        							checked: item.select_value

        						});




        					}//end of the item.type if statement



        			   } //end of the i for loop
        			   task_container.add(checkboxGroup_task);


        			   var values = {
        				name: task_name

        				};


        		   //form.loadRecord(record[0]);

        		   form.getForm().setValues(values);

        			}



        			});

        			win.show();


        		} else {
        				Ext.Msg.alert('Error', 'Please Select a Task ');

        		}
    },

    onTasksmainPanelRender: function(component, eOpts) {
        component.down('grid').getStore().load();
    },

    init: function(application) {
        this.control({
            "tasksmain button#createBtn": {
                click: this.onCreateNewTaskButtonClick
            },
            "tasksmain button#editBtn": {
                click: this.onEditTaskButtonClick
            },
            "tasksmain button#assignBtn": {
                click: this.onAssignTaskButtonClick
            },
            "tasksmain button#deleteBtn": {
                click: this.onDeleteTaskButtonClick
            },
            "newtaskwin button#createBtn": {
                click: this.onSaveCreatedTaskButtonClick
            },
            "edittaskwin button#editBtn": {
                click: this.onSaveEdittedTaskButtonClick
            },
            "assigntaskwin button#assignBtn": {
                click: this.onSaveAssignedTaskButtonClick
            },
            "tasksmain grid": {
                itemdblclick: this.onTaskGridpanelItemDblClick
            },
            "tasksmain": {
                render: this.onTasksmainPanelRender
            }
        });
    }

});
