/*
 * File: app/controller/WebsiteMembershipContentController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.controller.WebsiteMembershipContentController', {
    extend: 'Ext.app.Controller',

    models: [
        'WebsiteMembership'
    ],
    stores: [
        'WebsiteMembership'
    ],
    views: [
        'WebsiteMembershipForm',
        'WebsiteMembershipWin',
        'WebsiteMembershipMainpanel',
        'WebsiteMembershipGridpanel'
    ],

    refs: [
        {
            ref: 'allWebsiteMembershipContentGrid',
            selector: 'websitemembershipmainpanel grid'
        }
    ],

    onAddWebsiteMembershipContentButtonClick: function(button, e, eOpts) {
        var win = Ext.create('cobuy.view.WebsiteMembershipWin');

        win.show();
    },

    onEditWebsiteMembershipContentButtonClick: function(button, e, eOpts) {
        var grid = this.getAllWebsiteMembershipContentGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditWebsiteMembershipContentWin');
        			editWin.down('form').loadRecord(record[0]);
        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error', 'Please Select a website membership content to edit');
        		}
    },

    onDeleteThisWebsiteMembershipContentButtonClick: function(button, e, eOpts) {
        var grid = this.getAllWebsiteMembershipContentGrid();
        		var record= grid.getSelectionModel().getSelection();

        if(record[0]){


        	Ext.Msg.show({
                         title:'Delete?',
                         msg: 'Are you sure you want to delete this Website Membership Content?',
                         buttons: Ext.Msg.YESNO,
                         icon: Ext.Msg.QUESTION,
                         fn: function (buttonId){
                            if (buttonId == 'yes'){
                                Ext.Ajax.request({
                                    url: '/cobuy/index.php?r=WebsiteMembership/DeleteThisMembershipContent',
                                    params: {
                                        id: record[0].get('id')

                                    },
                                    success: function(conn, response, options, eOpts) {

                                        var result = Ext.JSON.decode(conn.responseText);

                                        if (result.success) {

                                            Ext.Msg.alert('Success!', result.msg);
                                            grid.getStore().load();

                                        } else {
                                            var error = Ext.JSON.decode(conn.responseText);
                                            Ext.Msg.alert('Error', error.msg);
                                        }
                                    },
                                    failure: function(conn, response, options, eOpts) {

                                        Ext.Msg.alert('Failure', 'Communication Error');
                                    }
                                });
                            }
                         }
                    });

        }else {
        				Ext.Msg.alert('Error', 'Please Select a Website Membership Content to delete');
        		}

    },

    onWebsiteMembershipContentGridpanelItemClick: function(dataview, record, item, index, e, eOpts) {
        var grid = this.getAllWebsiteMembershipContentGrid(),
        		record = grid.getSelectionModel().getSelection();

        		if(record[0]) {
        			var editWin = Ext.create('cobuy.view.EditWebsiteMembershipContentWin');
        			editWin.down('form').loadRecord(record[0]);
        			editWin.show();
        		} else {
        				Ext.Msg.alert('Error', 'Please Select a website membership content to edit');
        		}
    },

    onSaveWebsiteMembershipContentButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllWebsiteMembershipContentGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=WebsiteMembership/addNewWebsiteMembershipContent',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    onSaveEdittedWebsiteMembershipContentButtonClick: function(button, e, eOpts) {
        var win = button.up('window'),
        			formPanel = win.down('form'),
        			store = this.getAllWebsiteMembershipContentGrid().getStore();

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url: '/cobuy/index.php?r=WebsiteMembership/updateWebsiteMembershipContent',
                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Success!', result.msg);
                                    //Ext.Msg.alert('Success!', 'New  Group Information Saved.');
        							//store.load();
        							store.load();

        							win.close();
        						} else {
        							Ext.Msg.alert(result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Failure', result.msg);
        						}
        					}
        				});
        			}
    },

    init: function(application) {
        this.control({
            "websitemembershipmainpanel button#addBtn": {
                click: this.onAddWebsiteMembershipContentButtonClick
            },
            "websitemembershipmainpanel button#editBtn": {
                click: this.onEditWebsiteMembershipContentButtonClick
            },
            "websitemembershipmainpanel button#deleteBtn": {
                click: this.onDeleteThisWebsiteMembershipContentButtonClick
            },
            "websitemembershipmainpanel grid": {
                itemclick: this.onWebsiteMembershipContentGridpanelItemClick
            },
            "websitemembershipwin button#saveBtn": {
                click: this.onSaveWebsiteMembershipContentButtonClick
            },
            "editwebsitemembershipcontentwin button#saveBtn": {
                click: this.onSaveEdittedWebsiteMembershipContentButtonClick
            }
        });
    }

});
